[project]
name = "tg-bot"
version = "0.1.0"
dependencies = [
    "python-telegram-bot==20.7",
    "requests==2.31.0"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"